### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by r-barnes** [kesara/deepdreamer#26]
When I run it using the [bvlc_googlenet](https://github.com/BVLC/caffe/tree/master/models/bvlc_googlenet) (sha5: 405fc5acd08a3bb12de8ee5e23a96bec22f08204), I get the following:

```
Traceback (most recent call last):
  File "deepdreamer.py", line 110, in <module>
    main()
  File "deepdreamer.py", line 105, in main
    raise e
  File "deepdreamer.py", line 102, in main
    duration=args.duration, loop=loop, gpu=gpu, gpuid=args.gpuid)
  File "/home/rick/projects/meredith_animal_dreams/deepdreamer/deepdreamer/deepdreamer.py", line 180, in deepdream
    octave_scale=octave_scale, end=end, clip=clip)
  File "/home/rick/projects/meredith_animal_dreams/deepdreamer/deepdreamer/deepdreamer.py", line 104, in _deepdream
    _make_step(net, end=end, clip=clip, **step_params)
  File "/home/rick/projects/meredith_animal_dreams/deepdreamer/deepdreamer/deepdreamer.py", line 57, in _make_step
    dst = net.blobs[end]
KeyError: 'inception_4c/output
```

This same issue arose when trying to use [Google's original notebook](https://github.com/google/deepdream), so I think perhaps it is an issue with the `bvlc_googlenet` file.

**Comment by r-barnes** [comment]
It turns out I somehow had the wrong `deploy.prototxt` file. Using [this one](https://github.com/BVLC/caffe/blob/master/models/bvlc_googlenet/deploy.prototxt) fixed the issue.
