### ISSUE TITLE
ImportError: No module named images2gif - Ubuntu 16.04 Python 2.7

### ISSUE THREAD

**Issue by gateway** [kesara/deepdreamer#27]
Issue I have gotten but cant figure out how to get around.. I did pip install images2gif

```
gateway@gateway-evil:~/work/deepdreamer$ python2.7 deepdreamer.py --gif true image.jpg
Traceback (most recent call last):
  File "deepdreamer.py", line 9, in <module>
    from deepdreamer.deepdreamer import deepdream, deepdream_video, list_layers
  File "/home/gateway/work/deepdreamer/deepdreamer/deepdreamer.py", line 12, in <module>
    from deepdreamer.images2gif import writeGif
ImportError: No module named images2gif
```

Wanted to make sure I had the module.

```
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> 
>>> import sys
>>> 
>>> 
>>> 
>>> reqs = subprocess.check_output([sys.executable, '-m', 'pip', 'freeze'])
>>> 
>>> installed_packages = [r.decode().split('==')[0] for r in reqs.split()]
>>> 
>>> print(installed_packages)
[u'adium-theme-ubuntu', u'backports.functools-lru-cache', u'backports.shutil-get-terminal-size', u'cycler', u'Cython', u'decorator', u'dnspython', u'enum34', u'gyp', u'h5py', u'images2gif', u'images2gif-Pillow', u'ipython', u'ipython-genutils', u'kiwisolver', u'leveldb', u'matplotlib', u'networkx', u'nose', u'numpy', u'pandas', u'pathlib2', u'pexpect', u'pickleshare', u'Pillow', u'prompt-toolkit', u'protobuf', u'ptyprocess', u'pycrypto', u'pycurl', u'Pygments', u'pyparsing', u'Pyste', u'python-apt', u'python-dateutil', u'python-gflags', u'pytz', u'PyYAML', u'scandir', u'scikit-image', u'scipy', u'simplegeneric', u'six', u'subprocess32', u'traitlets', u'unity-lens-photos', u'wcwidth']
>>> 
```
notice u'images2gif is listed.

any suggestions?

**Comment by uajqq** [comment]
See comment #20 — I’m just using Pillow in my fork to make the gifs.
